var main, err, res;
main = function (callback) {
  var result;
  (function (_$cont) {
    try {
      setTimeout(function (arguments) {
        try {
          result = 0;
          [
            10,
            20,
            30
          ].forEach(function (i) {
            result += i;
            throw Error('Oops');
          });
          _$cont();
        } catch (_$err) {
          _$cont(_$err);
        }
      }.bind(this, arguments), 0);
    } catch (_$err) {
      _$cont(_$err);
    }
  }(function (e) {
    if (e !== undefined) {
      callback(e);
      return;
    }
    callback(null, result);
  }));
};
main(function (arguments, _$param0, _$param1) {
  err = _$param0;
  res = _$param1;
  console.log('main() finished with', err, res);
}.bind(this, arguments));
/* Generated by Continuation.js v0.1.7 */